import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Privacy Policy",
    description: "Vysera Privacy Policy",
    alternates: {
        canonical: "https://getvysera.com/privacy-policy",
    },
}

export default function PrivacyPolicy() {
    return (
        <div>
            <link rel="stylesheet" href="/css/pricing.css" />

            <section className="pricing-page-header">
                <div className="container">
                    <div className="badge">Privacy Policy</div>
                    <h1>Privacy Policy</h1>
                </div>
            </section>

            <section className="pricing-container">
                <p className="text-xl text-left text-gray-600 mb-16 mx-auto">
                    Last Updated: January 03, 2026
                    <br /><br />
                    This Privacy Policy describes how Argares ("we," "us," or "our") collects, uses, and discloses your information
                    when you use our document reminder service (the "Service") and tells you about your privacy rights and how the
                    law protects you.
                    <br /><br />
                    <b>1. Definitions and Interpretation</b><br />
                    Account: A unique account created for You to access our Service.
                    <br /><br />
                    Company: Refers to Argares, Jakarta, Indonesia.
                    <br /><br />
                    Personal Data: Any information that relates to an identified or identifiable individual.
                    <br /><br />
                    Service: Refers to the Vysera application and website.
                    <br /><br />
                    User Data (Non-Personal Data): Refers to the documents, files, and content uploaded by you for the purpose of
                    the reminder service.
                    <br /><br />
                    Usage Data: Data collected automatically, either generated by the use of the Service or from the Service
                    infrastructure itself (e.g., the duration of a page visit).
                    <br /><br />
                    <b>2. Data We Collect</b><br />
                    We collect several different types of information for various purposes to provide and improve our Service to
                    You.
                    <br /><br />
                    <b>2.1. Personal Data</b><br />
                    While using our Service, we may ask you to provide us with certain personally identifiable information that can
                    be used to contact or identify You. Personally identifiable information may include, but is not limited
                    to:<br />
                    - Email address<br />
                    - First name and last name<br />
                    - Payment information (processed by a secure third-party payment processor)<br /><br />
                    <b>2.2. User Data (Uploaded Documents)</b><br />
                    The core function of the Service involves You uploading documents and files. We collect and store these files.
                    <br /><br />
                    Content: We store the files (e.g., PDFs, images) that you upload.
                    <br /><br />
                    Metadata: We store metadata associated with the files, such as file names, file types, upload dates, and the
                    reminder schedules you set.
                    <br /><br />
                    Commitment: We do not examine, analyze, or process the content of your User Data for marketing purposes. Access
                    to User Data is strictly limited to authorized personnel only when technically necessary to provide support or
                    maintain the Service.
                    <br /><br />
                    <b>2.3. Usage Data</b><br />
                    We automatically collect information when the Service is accessed, such as:
                    <br />
                    - Your computer's Internet Protocol address (e.g., IP address).<br />
                    - Browser type and version.<br />
                    - The pages of our Service that you visit.<br />
                    - The time and date of your visit.<br />
                    - Device type (e.g., mobile or desktop).<br /><br />
                    <b>3. How We Use Your Data</b><br />
                    We use the collected data for various purposes:
                    <br /><br />
                    To provide and maintain the Service, including monitoring the usage of the Service.

                    To manage your Account and register you as a user of the Service.
                    <br /><br />
                    To perform the contract for the document reminder service (i.e., sending you reminders about your uploaded
                    documents).

                    To contact You by email regarding updates or informative communications related to the Service.
                    <br /><br />
                    For billing and payment processing (through secure third-party services).
                    <br /><br />
                    To improve the Service and develop new features based on usage trends.
                    <br /><br />
                    <b>4. How Your Data is Stored and Secured</b><br />
                    <b>4.1. Data Storage</b><br />
                    Object Storage: User Data (uploaded documents) is stored securely on third-party object storage platforms (e.g.,
                    Wasabi, AWS S3) which are designed for high durability and redundancy.
                    <br /><br />
                    Location: Following the provider's location.
                    <br /><br />
                    <b>4.2. Security Measures</b><br />
                    The security of your Personal Data and User Data is important to us, but remember that no method of transmission
                    over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable
                    means to protect your data, we cannot guarantee its absolute security.
                    <br /><br />
                    We use industry-standard encryption protocols (SSL/TLS) for data transmission.
                    <br /><br />
                    Access to User Data is protected by strong authentication and authorization protocols.
                    <br /><br />
                    <b>5. Disclosure of Your Personal Data</b><br />
                    We may share your personal information in the following situations:
                    <br /><br />
                    With Service Providers: We may share your Personal Data with third-party vendors to facilitate our Service, to
                    perform Service-related services, or to assist us in analyzing how our Service is used (e.g., payment
                    processors, email service providers).
                    <br /><br />
                    For Legal Reasons: If required to do so by law or in response to valid requests by public authorities (e.g. a
                    court or a government agency).

                    Business Transfers: If we are involved in a merger, acquisition, or asset sale, your Personal Data may be
                    transferred.
                    <br /><br />
                    <b>6. Links to Other Websites</b><br />
                    Our Service may contain links to other websites that are not operated by us. If you click on a third-party link,
                    you will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every
                    site You visit.
                    <br /><br />
                    <b>7. Changes to this Privacy Policy</b><br />
                    We may update our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy
                    Policy on this page. You are advised to review this Privacy Policy periodically for any changes.
                    <br /><br />
                    <b>8. Contact Us</b><br />
                    If you have any questions about this Privacy Policy, You can contact us at: hello@getvysera.com.
                    <br /><br />
                </p>
            </section>
        </div>
    );
}