import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";
import "./globals.css";

import { GoogleAnalytics } from '@next/third-parties/google'
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vysera - Employee Certification & Compliance Tracking",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {/* Title is handled by Next.js metadata export */}
        <meta name="description"
          content="Ensure enterprise compliance with Vysera. Automate employee contract renewals, credentials, training and license certificate expirations to mitigate legal risks, avoid costly penalties, and maintain audit-ready documentation in one secure platform." />
        <meta name="keywords"
          content="Vysera, Contract Compliance Software, Regulatory Risk Mitigation, Enterprise Renewal Tracking, Automated Audit Trail, Legal Document Management, License Compliance Tool, Contract Governance, Expiration Risk Management, Corporate Compliance Automation, employee credential tracking, employee certification tracking, employee training tracking, work premit expiration reminder, work contact tracker" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="/css/style.css" />
        <link rel="stylesheet" href="/css/mobile-menu.css" />

        <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png" />
        <link rel="manifest" href="/favicon/site.webmanifest" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://getvysera.com/" />
        <meta property="og:title" content="Employee Certification Tracking Software" />
        <meta property="og:description"
          content="Ensure enterprise compliance with Vysera. Automate employee contract renewals, credentials, training and license certificate expirations to mitigate legal risks, avoid costly penalties, and maintain audit-ready documentation in one secure platform." />
        <meta property="og:image" content="/img/getvysera.png" />

        <meta property="twitter:card" content="summary_large_image" />
        <meta property="twitter:title" content="Employee Certification Tracking Software" />
        <meta property="twitter:description"
          content="Ensure enterprise compliance with Vysera. Automate employee contract renewals, credentials, training and license certificate expirations to mitigate legal risks, avoid costly penalties, and maintain audit-ready documentation in one secure platform." />
        <meta property="twitter:image" content="/img/getvysera.png" />
        <meta name="robots" content="index, follow" />
        <meta name="google-site-verification" content="" />

        <Script
          strategy="afterInteractive"
          src={`https://www.googletagmanager.com/gtag/js?id=G-BD766VL5D4`}
        />
        <Script
          id="google-analytics"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-BD766VL5D4');
          `,
          }}
        />

      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
